@host=https://localhost:7170

GET ({host})/dinners/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxZGQ0MjM3MS0yNTllLTRiMWYtYmEwNy0xNDhiNzA2Y2I4ZmMiLCJnaXZlbl9uYW1lIjoiU2NvdHQiLCJmYW1pbHlfbmFtZSI6IlZhdWdoYW4iLCJqdGkiOiIwZWJlZjBlYS0wZjhlLTQwZmEtYTY2ZS1jM2NlYWVjYTY5NTEiLCJleHAiOjE2NzA5MjA2MjYsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.8kdgkwdTufgC-BiXVFkJadHAinUyZcn4-9P_3wI-q-k